Algoritmo "Vetoresex2"
// Disciplina   : [PA]
// Professor   : Cintia Pinho
// Descrição   : testando vetores e suas funcionalidades
// Autor(a)    : isadora walesca alves duarte
// Data atual  : 30/09/2021
Var
vet : vetor (1...5) de inteiro
N:inteuiro
Inicio
escreval("Digite um valor inteiro")
leia(vent(1))
para n de 2 até a 5 faça
vent(n)<- (n-1) + 2
//imprimir
para n de 2 até a 5 faça
escreval(vet(n)"")
fimpara
Fimalgoritmo